// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0nNKp7oQ06mawothVuScWIiMaY8Ev6dQ',
    appId: '1:990529227465:android:218d6e3414b7b8de431b18',
    messagingSenderId: '990529227465',
    projectId: 'roadresq-bd6b0',
    storageBucket: 'roadresq-bd6b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmrGN5ST-5pOYbU3UQDuxob0dzoWHZF-w',
    appId: '1:990529227465:ios:60d4d73372c46da2431b18',
    messagingSenderId: '990529227465',
    projectId: 'roadresq-bd6b0',
    storageBucket: 'roadresq-bd6b0.firebasestorage.app',
    androidClientId: '990529227465-4hgqv3ifmv2gjphsl1c3pm3o8579ajj4.apps.googleusercontent.com',
    iosClientId: '990529227465-9f8o64c7qv2tbrd51u25o7jsc6f2fe73.apps.googleusercontent.com',
    iosBundleId: 'com.example.roadResq',
  );
}
